// Generated by CoffeeScript 1.4.0

jQuery(document).ready(function($) {
  var barClasses, barData, barWidth, bars, cellPadding, cellSize, color, day, dayOfMonth, format, height, month, monthPath, percent, processTemplate, rect, svg, week, width;
  monthPath = function(t0) {
    var d0, d1, t1, w0, w1;
    t1 = new Date(t0.getFullYear(), t0.getMonth() + 1, 0);
    d0 = +day(t0);
    w0 = +week(t0);
    d1 = +day(t1);
    w1 = +week(t1);
    return "M" + (w0 + 1) * cellSize + "," + d0 * cellSize + "H" + w0 * cellSize + "V" + 7 * cellSize + "H" + w1 * cellSize + "V" + (d1 + 1) * cellSize + "H" + (w1 + 1) * cellSize + "V" + 0 + "H" + (w0 + 1) * cellSize + "Z";
  };
  processTemplate = function(template, params) {
    return template.replace(/{{opportunities}}/ig, params.opportunities).replace(/{{tNum1}}/ig, params.tNum1).replace(/{{tNum2}}/ig, params.tNum2).replace(/{{tNum3}}/ig, params.tNum3).replace(/{{eNum1}}/ig, params.eNum1).replace(/{{eNum2}}/ig, params.eNum2).replace(/{{eNum3}}/ig, params.eNum3);
  };
  width = 800;
  height = 136;
  cellSize = 15;
  cellPadding = 1.2;
  day = d3.time.format("%w");
  dayOfMonth = d3.time.format("%d");
  week = d3.time.format("%U");
  month = d3.time.format("%b");
  percent = d3.format(".1%");
  format = d3.time.format("%Y-%m-%d");
  color = d3.scale.quantize().domain([0, 100]).range(d3.range(5).map(function(d) {
    return "q" + d + "-11";
  }));
  barData = [
    {
      opportunities: 3,
      tNum1: 50478,
      tNum2: 15300,
      tNum3: 5800,
      eNum1: 10500,
      eNum2: 55300,
      eNum3: 4300
    }, {
      opportunities: 5,
      tNum1: 98675,
      tNum2: 15300,
      tNum3: 5800,
      eNum1: 10500,
      eNum2: 55300,
      eNum3: 4300
    }, {
      opportunities: 2,
      tNum1: 17456,
      tNum2: 15300,
      tNum3: 5800,
      eNum1: 10500,
      eNum2: 55300,
      eNum3: 4300
    }
  ];
  barWidth = d3.scale.linear().domain([
    0, d3.sum(barData.map(function(d) {
      return d.tNum1;
    }))
  ]).range([0, 100]);
  barClasses = d3.scale.quantize().domain([0, 2]).range(['success', 'warning', 'danger']);
  bars = d3.select('body>div.container').insert("div", "body>div.main-container").attr('class', 'progress progress-striped');
  bars.selectAll('div').data(barData).enter().append("div").attr("class", function(d, i) {
    return "row-fluid item bar bar-" + barClasses(i);
  }).style('width', function(d, i) {
    return barWidth(d.tNum1) + "%";
  }).html(function(d, i) {
    return processTemplate($("#barData").html(), barData[i]);
  });
  svg = d3.select("body>div.main-container").append("svg").data(d3.range(2013, 2014)).enter().append("svg").attr("width", width).attr("height", height).attr("class", "RdYlGn").append("g").attr("transform", "translate(" + ((width - cellSize * 53) / 2) + "," + (height - cellSize * 7 - 1) + ")");
  svg.append("text").attr("transform", "translate(-6," + cellSize * 3.5 + ")rotate(-90)").attr("class", "text-month").style("text-anchor", "middle").text(function(d) {
    return d;
  });
  rect = svg.selectAll(".day").data(function(d) {
    return d3.time.days(new Date(d, 0, 1), new Date(d + 1, 0, 1));
  }).enter().append("rect").attr("class", function(d, i) {
    return "day " + color(bData[i].value);
  }).attr("width", cellSize - cellPadding * 2).attr("height", cellSize - cellPadding * 2).attr("x", function(d) {
    return week(d) * cellSize + cellPadding;
  }).attr("y", function(d) {
    return day(d) * cellSize + cellPadding;
  }).each(function(d) {
    if (day(d) * cellSize === 0 && dayOfMonth(d) <= 7) {
      return svg.append("text").text(month(d)).attr("class", "text-month").attr("x", function() {
        return week(d) * cellSize + 5;
      }).attr("y", -5);
    }
  }).attr("data-title", function(d, i) {
    return "Date: " + bData[i].date + "<br/> Percentage: " + bData[i].value;
  }).datum(format);
  $("div.main-container").append($("svg"));
  return $("rect.day").qtip({
    content: {
      text: function(api) {
        return $(this).data("title");
      }
    },
    position: {
      my: "bottom center",
      at: "top center"
    },
    hide: {
      fixed: false
    },
    style: "qtip-dark custom-tooltip qtip-rounded"
  });
});
